apiVersion: v1
metadata:
  name: {{ include "vault-backup.fullname" . }}
  labels:
    {{- include "vault-backup.labels" . | nindent 4 }}
type: Opaque
data:
  VAULT_TOKEN: {{ .Values.vault.token | b64enc }}
  {{- if and .Values.s3.accessKey .Values.s3.secretKey }}
  S3_ACCESS_KEY: {{ .Values.s3.accessKey | b64enc }}
  S3_SECRET_KEY: {{ .Values.s3.secretKey | b64enc }}
  {{- end }}
kind: Secret