name: Release application
on:
  release:
    types:
      - published

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get the package version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          username: alv91
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish backend application
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: alv91/vault-backup:${{ steps.get_version.outputs.VERSION }},alv91/vault-backup:latest
          platforms: linux/amd64,linux/arm64
